### ISSUE TITLE
idsite not set

### ISSUE THREAD

**Issue by mjvanderveen** [mgazdzik/plugin-ShortcodeTracker#47]
Hi, using plugin version 2.0.1 in matomo version 4.4.1 the idsite set in the plugin configuration is not set in the database when creating a shortcode url. It's instead set at 0, generating a tracking failure.

**Comment by mgazdzik** [comment]
@mjvanderveen can you provide more details of the problem you're experiencing? for ex. what domains are set for your configured websites, did you set the external redirects site and what url are you shortening? just recently I've gone through some debugging of plugin and it seems that generating as well as tracking are working fine.

Closing the issue for now due to it's age, please reopen if the problem still exists.
