### ISSUE TITLE
How do I delete\edit existing shortcode

### ISSUE THREAD

**Issue by plegault3397** [mgazdzik/plugin-ShortcodeTracker#56]
Is it possible to edit or delete existing shortcodes?

**Comment by mgazdzik** [comment]
Unfortunately it's not possible to do any of those actions.
Deleting - I figured out that it would take really lots of shortcodes to create any significant load on Matomo database (especially compared to other tables like log_visit or log_visit_action).

As for editing - since codes are generated automatically I didn't see any reason for editing them too. Additionally, editing just the shortcode would not change the shortcode redirects stored so far in events table and thus data would become inconsistent (i.e. in some reports you'd start seeing two shortcodes while it's the same entity).

**Comment by plegault3397** [comment]
It would be nice to be able to delete entries.
